### ISSUE TITLE
pip install failing

### ISSUE THREAD

**Issue by mbernico** [viisar/brew#21]
Seems like a packaging problem... See requirements.txt error

$ pip install brew -v
Collecting brew
  1 location(s) to search for versions of brew:
  * https://pypi.python.org/simple/brew/
  Getting page https://pypi.python.org/simple/brew/
  Looking up "https://pypi.python.org/simple/brew/" in the cache
  Current age based on date: 673
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The cached response is "stale" with no etag, purging
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/brew/ HTTP/1.1" 200 449
  Updating cache with response from "https://pypi.python.org/simple/brew/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/brew/
    Found link https://pypi.python.org/packages/4d/d7/ea56c3726e7539d80c9a2d3c67ceaa1008cf5802e9bf552a2413b004f7b9/brew-0.1.3.zip#md5=d504cc9c1d97782ccd1979ef493b56fb (from https://pypi.python.org/simple/brew/), version: 0.1.3
    Found link https://pypi.python.org/packages/71/19/75f6d42ca862c6b31e2da9864d94f59fe81978ac5d40c43937a1c17fd065/brew-0.1.4.zip#md5=2f9561aea0c754570bc03f05e2dcbb8c (from https://pypi.python.org/simple/brew/), version: 0.1.4
    Found link https://pypi.python.org/packages/b3/c6/ab3328b05bcf3bfb6e453ddb18ae356f9b167dcfec0ab1bf2289c48bade2/brew-0.1.1.zip#md5=a3aaec2c55d9ca1284a715bc5f5caeec (from https://pypi.python.org/simple/brew/), version: 0.1.1
    Found link https://pypi.python.org/packages/cf/67/65d3ea968f55f9ac12e052476cbf7e950aa5d740ff24339f1feaf425934c/brew-0.1.2.zip#md5=75fc2c9ea0eb7c97b7f26dc6454f27a6 (from https://pypi.python.org/simple/brew/), version: 0.1.2
  Using version 0.1.4 (newest of versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4)
  Looking up "https://pypi.python.org/packages/71/19/75f6d42ca862c6b31e2da9864d94f59fe81978ac5d40c43937a1c17fd065/brew-0.1.4.zip" in the cache
  Current age based on date: 673
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 673
  Using cached brew-0.1.4.zip
  Downloading from URL https://pypi.python.org/packages/71/19/75f6d42ca862c6b31e2da9864d94f59fe81978ac5d40c43937a1c17fd065/brew-0.1.4.zip#md5=2f9561aea0c754570bc03f05e2dcbb8c (from https://pypi.python.org/simple/brew/)
  Running setup.py (path:/tmp/pip-build-xfh1r8uw/brew/setup.py) egg_info for package brew
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xfh1r8uw/brew/setup.py", line 22, in <module>
        with open('requirements.txt') as fid:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xfh1r8uw/brew/
Exception information:
Traceback (most recent call last):
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/req/req_set.py", line 601, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/req/req_install.py", line 425, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/mike/anaconda/lib/python3.5/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xfh1r8uw/brew/

**Comment by dvro** [comment]
We'll look into it, @mbernico.

In the meantime, you can install it using

```
pip install git+https://github.com/viisar/brew.git
````
