### ISSUE TITLE
Error on install - Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-KJHgg7/brew/

### ISSUE THREAD

**Issue by thHawat** [viisar/brew#29]
Hi,

I'm on Mac OS 10.12.4

I cannot install brew. 
pip install brew fails :

(root) MacBook-Pro-de-Didier:Octopus Didier$ sudo -H pip install brew
Collecting brew
  Downloading brew-0.1.4.zip (48kB)
    100% |████████████████████████████████| 51kB 309kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-KJHgg7/brew/setup.py", line 22, in <module>
        with open('requirements.txt') as fid:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-KJHgg7/brew/

I also tried sudo pip install brew, and sudo -H pip install brew.

Thanks for your help.

**Comment by paulochf** [comment]
+1
