### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KQWXG9/brew/

### ISSUE THREAD

**Issue by va26** [viisar/brew#34]
When I run `$ pip install brew` on Python 2.7.14 :: Anaconda, Inc., ubuntu 17.10, I get the following error:
```
(Python27) vat26@vatsal:~$ pip install brew
Collecting brew
  Using cached brew-0.1.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KQWXG9/brew/setup.py", line 22, in <module>
        with open('requirements.txt') as fid:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KQWXG9/brew/
```

**Comment by va26** [comment]
Yeah! Actually `pip install brew` gives this error but you use the second command `pip install git+https://github.com/viisar/brew.git`. This worked for me.

**Comment by anjali-123b** [comment]
Hello,
I tried this too. But then I get the error 'Cannot find command git'. How do I remedy this?

**Comment by va26** [comment]
Install git on you system using the following [link for ubuntu](https://www.digitalocean.com/community/tutorials/how-to-install-git-on-ubuntu-16-04) and [link for windows](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
